.TH od65 1 "August 2021" "0.1.0" "User Manuals"
.SH NAME
od65 \- cc65 object file dump utility

.SH SYNOPSIS
od65 [\fIoptions\fR] \fIfile\fR [\fIoptions\fR] [\fIfile\fR]

.SH DESCRIPTION
od65 is an object file dump utility. It is able to output most parts of
ca65-generated object files in readable form. Since the contents and format of
the object files are not documented elsewhere and may change at any time, this
tool is a portable way to look at the contents.

Apart from curiosity, most people don't need to use this tool.

.SH OPTIONS

.TP
.BR \-h ", " \-\-help
Print short option summary

.TP
.BR \-H ", " \-\-dump\-header
Dump the object file header

.TP
.BR \-S ", " \-\-dump\-segsize
Dump segments sizes

.TP
.BR \-V ", " \-\-version
Print the version number and exit

.TP
.B \-\-dump\-all
Dump all object file information

.TP
.B \-\-dump\-dbgsyms
Dump debug symbols

.TP
.B \-\-dump\-exports
Dump exported symbols

.TP
.B \-\-dump\-files
Dump the source files

.TP
.B \-\-dump\-imports
Dump imported symbols

.TP
.B \-\-dump\-lineinfo
Dump line information

.TP
.B \-\-dump\-options
Dump object file options

.TP
.B \-\-dump\-segments
Dump the segments in the file
.TP
.B \-\-dump\-scopes
Dump scope information

.SH DETAILED OPTIONS

.TP
.B \-\-dump\-all
This will output all information, od65 is able to process. The option is a
shortcut for specifying all the other \-\-dump options.

.TP
.B \-\-dump\-dbgsyms
Dump all debug symbols contained in the object file.

.TP
.B \-\-dump\-exports
Dump all exported symbols contained in the object file.

.TP
.B \-\-dump\-files
Dump the file table contained in the object file.

.TP
.BR \-H ", " \-\-dump\-header
Dump the object file header.

.TP
.B \-\-dump\-imports
Dump the list of imported symbols contained in the object file.

.TP
.B \-\-dump\-lineinfo
Dump the line info contained in the object file.

.TP
.B \-\-dump\-segments
Dump the list of segments contained in the object file.

.TP
.B \-\-dump\-scopes
Dump the scope (lexical level) information contained in the object file.

.TP
.BR \-S ", " \-\-dump\-segsize

Dump the sizes of all segments contained in the object file. This option is
quite useful to determine the effect of measures that increase or decrease code
size.

.TP
.BR \-h ", " \-\-help
Print the short option summary shown above.

.TP
.BR \-V ", " \-\-version
Print the version number of the compiler. When submitting a bug report, please
include the operating system you're using, and the compiler version.

.SH INPUT & OUTPUT
The converter will read one or more object files per invocation and write the
contents in readable format to standard output. Please note that you need to
specify any of the \-\-dump options listed above, otherwise no useful output will
be generated.

Example output for the command

.RS
od65 --dump-header --dump-files t.o

t.o:
  Header:
    Magic:                 0x616E7A55
    Version:                       12
    Flags:                     0x0001  (OBJ_FLAGS_DBGINFO)
    Options:
      Offset:                      88
      Size:                         9
    Files:
      Offset:                      97
      Size:                        10
    Segments:
      Offset:                     107
      Size:                       101
    Imports:
      Offset:                     208
      Size:                         1
    Exports:
      Offset:                     209
      Size:                         1
    Debug symbols:
      Offset:                     210
      Size:                        55
    Line infos:
      Offset:                     265
      Size:                         1
    String pool:
      Offset:                     266
      Size:                        80
  Files:
    Count:                          1
    Index:                          0
      Name:                     "t.s"
      Size:                       402
      Modification time:   1280498435  (Fri Jul 30 16:00:35 2010)
.RE

.SH AUTHOR
Program Author: Ullrich von Bassewitz <webmaster@von-bassewitz.de>
.br
Manpage Author: Jake Grossman         <jake.r.grossman@gmail.com>

.SH COPYRIGHT
od65 (C) Copyright 2000-2009 Ullrich von Bassewitz
and others. For usage of the binaries and/or sources the following conditions do
apply:

This software is provided 'as-is', without any expressed or implied warranty. In
no event will the authors be held liable for any damages arising from the use of
this software.

Permission is granted to anyone to use this software for any purpose, including
commercial applications, and to alter it and redistribute it freely, subject to
the following restrictions:

.IP 1.
The origin of this software must not be misrepresented; you must not claim that
you wrote the original software. If you use this software in a product, an
acknowledgment in the product documentation would be appreciated but is not
required.

.IP 2.
Altered source versions must be plainly marked as such, and must not be
misrepresented as being the original software.

.IP 3.
This notice may not be removed or altered from any source distribution.

.SH SEE ALSO
.B cc65(1),
.B ca65(1)
