.Dd $Mdocdate$
.Dt SIM65 1 URM
.Os 0.1.0
.Sh NAME
.Nm sim65
.Nd a 6502/65C02 CPU simulator
.Sh SYNOPSIS
.Nm
.Bk -words
.Op Fl hcV
.Op Fl x Ar num-cycles
.Ek
.Sh DESCRIPTION
sim65 is used as part of the toolchain to test 6502 or 65C02 code.
The binary to test should be compiled with --target sim6502 or --target sim65c02.
.Sh OPTIONS
.Bl -tag -width "xxxxxxxxxxxxxx"
.It Fl h , Fl Fl help
Print a short option summary.
.It Fl c , Fl Fl cycles
Print the number of executed CPU cycles when the program terminates.
The cycles for the final "jmp exit" are not included in this count.
.It Fl V , Fl Fl V
Print the version number of the utility.
When submitting a bug report,
please include the operating system you're using,
and the compiler version.
.It Op Fl x Ar num-cycles
Exit simulation after 
.Em num
cycles.
.Sh INPUT & OUTPUT
The simulator will read one binary file per invocation and can log the program
loading and paravirtualization calls to stderr.
.Pp
Example output for the command:
.Bd -literal -offset indent
sim65 --verbose --verbose samples/gunzip65

Loaded 'samples/gunzip65' at $0200-$151F
PVWrite ($0001, $13C9, $000F)
GZIP file name:PVWrite ($0001, $151F, $0001)

PVRead ($0000, $FFD7, $0001)
PVOpen ("", $0001)
PVRead ($0003, $1520, $6590)
PVClose ($0003)
PVWrite ($0001, $13D9, $000F)
Not GZIP formatPVWrite ($0001, $151F, $0001)

PVExit ($01)
.Ed
.Sh CREATING A TEST IN C
For a C test compiled and linked with --target sim6502 the command line
arguments to sim65 will be passed to main,
and the return value from main will become sim65's exit code.
The exit function may also be used to terminate with an exit code.
.Pp
Exit codes are limited to 8 bits.
.Pp
The standard C library high level file input and output is functional.
A sim65 application can be written like a command line application,
providing arguments to main and using the stdio.h interfaces.
.Pp
Internally, file input and output is provided at a lower level by a set of
built-in paravirtualization functions (see below).
.Sh CREATING A TEST IN ASSEMBLY
Assembly tests may similarly be assembled and linked with --target sim6502 or
--target sim65c02, and the sim65 library provides an exit symbol that the
program may JMP to terminate with the current A register value as an exit code.
.Pp
The binary file has a 12 byte header:
.Bl -dash
.It
a 5 byte signature: $73, $69, $6D, $36, $35 or 'sim65'
.It
a 1 byte version indication: 2
.It
a 1 byte CPU type indication: 0 = 6502, 1 = 65C02
.It
a 1 byte sp address: the zero page address of the C parameter stack pointer sp
used by the paravirtualization functions
.It
a 1 word load address: where to load the data from the file into memory
(default: $0200)
.It
a 1 word reset address: specifies where to begin execution after loading
(default: $0200)
.El
.Pp
Other internal details:
.Bl -dash
.It
The entire 64 kilobyte address space is writeable RAM. Aside from the loaded
binary, the reset vector at $FFFC will be pre-loaded with the given reset
address.
.It
The exit address is $FFF9. Jumping to this address will terminate execution
with the A register value as an exit code.
.It
Several bytes immediately below the vector table are reserved for
paravirtualization functions. Except for exit, a JSR to one of these addresses
will return immediately after performing a special function. These use cc65
calling conventions, and are intended for use with the sim65 target C library.
.It
IRQ and NMI events will not be generated, though BRK can be used if the IRQ
vector at $FFFE is manually prepared by the test code.
.El
.Sh AUTHORS
Program Author: Ullrich von Bassewitz <\fIwebmaster@von-bassewitz.de\fR>
.br
Manpage Author: Jake Grossman         <\fIjake.r.grossman@gmail.com\fR>
.Sh COPYRIGHT
sim65 (and all cc65 binutils) are (C) Copyright 1998-2000 Ullrich von Bassewitz
and others. For usage of the binaries and/or sources the following conditions do
apply:
.Pp
This software is provided 'as-is', without any expressed or implied warranty. In
no event will the authors be held liable for any damages arising from the use of
this software.
.Pp
Permission is granted to anyone to use this software for any purpose, including
commercial applications, and to alter it and redistribute it freely, subject to
the following restrictions:
.Bl -enum
.It 1.
The origin of this software must not be misrepresented; you must not claim that
you wrote the original software. If you use this software in a product, an
acknowledgment in the product documentation would be appreciated but is not
required.
.It 2
Altered source versions must be plainly marked as such, and must not be
misrepresented as being the original software.
.It 3
This notice may not be removed or altered from any source distribution.
.Sh SEE ALSO
.Xr cc65 1 ,
.Xr ca65 1
.\" vim: set ts=4 sts=4 sw=4 et tw=60 :
